### PR TITLE
Remove `++` that doesn't do anything

### PR DESCRIPTION
**Pull request by remram44**
Looks like a typo. The actual incrementing of the seed is done line 34.

### CODE REVIEW

**Comment by queer** [comment]
Removing this would likely affect existing cards; I can test in a little bit.

**Comment by remram44** [comment]
It doesn't affect existing cards, `seed++` evaluates to `seed` and then increments it, but the variable is never used again.

**Comment by queer** [comment]
I don't remember my JS semantics too well, unfortunately :confounded: Would this not mutate the argument passed in?

**Comment by remram44** [comment]
It made my doubt when I saw your code, but numbers are passed by value so it's fine (I checked).

**Pull request merged**
